fdbc_resto_core:
    resource: "@FdbcRestoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

fdbc_resto_api_v1:
    resource: "@FdbcRestoApiV1Bundle/Controller/"
    type:     annotation
    prefix:   /

