NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# fdbc_resto_api_v1:
#     resource: "@FdbcRestoApiV1Bundle/Controller/"
#     type:     annotation
#     prefix:   /api/

fdbc_resto_api_v1:
    type:     rest
    resource: Fdbc\Resto\ApiV1Bundle\Controller\RestaurantController